### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Jie-Yuan** [shenweichen/DeepCTR#13]
![image](https://user-images.githubusercontent.com/20265321/50205826-958bd580-03a4-11e9-8e2d-fb5fbed0d048.png)

**Comment by shenweichen** [comment]
Hi, @Jie-Yuan  
I'm sorry for that the current version has only been tested for **tensorflow 1.4/1.5/1.6**
I think this error is caused by a higher version of tensorflow.
You can install a lower version of tensorflow to use deepctr.
Now I am updating the code to adapt to a higher version of tensorflow.
