### ISSUE TITLE
Embedding size in dien

### ISSUE THREAD

**Issue by rajeshshrestha** [shenweichen/DeepCTR#165]
I have not been able to change embedding size of dien model other than 8. I am getting error while using size other than 8.

**Comment by zanshuxun** [comment]
Please use the bug report template to show the error and reproduction.

**Describe the bug**
A clear and concise description of what the bug is.Better with standalone code to reproduce the issue.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment:**
 - python version [e.g. 3.6, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.5.0]
 - deepctr version [e.g. 0.8.6,]

**Additional context**
Add any other context about the problem here.
