### ISSUE TITLE
can not use deepctr

### ISSUE THREAD

**Issue by hallucination11** [shenweichen/DeepCTR#307]
AttributeError: module 'deepctr' has no attribute 'estimator'

**Comment by hallucination11** [comment]
AttributeError: module 'deepctr' has no attribute 'estimator'

**Comment by zanshuxun** [comment]
please use the bug report template:

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.3.0]
 - deepctr version [e.g. 0.8.2,]

**Additional context**
Add any other context about the problem here.

**Comment by hallucination11** [comment]
> please use the bug report template:
> 
> **Describe the bug(问题描述)**
> A clear and concise description of what the bug is.
> 
> **To Reproduce(复现步骤)**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Operating environment(运行环境):**
> 
> * python version [e.g. 3.5, 3.7]
> * tensorflow version [e.g. 1.4.0, 1.15.0, 2.3.0]
> * deepctr version [e.g. 0.8.2,]
> 
> **Additional context**
> Add any other context about the problem here.
