### ISSUE TITLE
csv转tfrecords,送入模型失败，提示: Data type int64, but except type float

### ISSUE THREAD

**Issue by Nicolezjy** [shenweichen/DeepCTR#321]
数据集预处理

**Describe the question(问题描述)**
数据集预处理，送入estimater模型无法运行

**Additional context**
1.下载CTR数据集：https://storage.googleapis.com/dataset-uploader/criteo-kaggle/large_version/eval.csv
https://storage.googleapis.com/dataset-uploader/criteo-kaggle/large_version/train.csv
2.拉开源代码将train.csv和eval.csv转成tfrecords：https://github.com/IntelAI/models/blob/master/models/recommendation/tensorflow/wide_deep_large_ds/dataset/preprocess_csv_tfrecords.py
3. 送到estimator模型，DeepCTR/examples/run_estimator_tfrecord_classification.py，运行，提示Data type int64, but except type float

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.5.0, 2.4.0]
 - deepctr version [e.g. 0.8.3,]

**Comment by zanshuxun** [comment]
请使用Bug report模板

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.4.0]
 - deepctr version [e.g. 0.8.3,]

**Additional context**
Add any other context about the problem here.
