### ISSUE TITLE
WDL 模型进行TF serving报错

### ISSUE THREAD

**Issue by Hanlos** [shenweichen/DeepCTR#351]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
WDL 模型进行TF serving报错
{'error': '{{function_node __inference__wrapped_model_164377_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_at_tf_graph}} {{function_node __inference__wrapped_model_164377_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_at_tf_graph}} transpose expects a vector of size 2. But input(1) is a vector of size 3\n\t [[{{node functional_1/sequence_pooling_layer_2/ArithmeticOptimizer/ReorderCastLikeAndValuePreserving_bool_transpose}}]]\n\t [[StatefulPartitionedCall/StatefulPartitionedCall]]'}

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.5.0, 2.4.0]
 - deepctr version [e.g. 0.8.3,]

**Comment by zanshuxun** [comment]
请按照bug report模板给出运行环境及复现步骤

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.Better with standalone code to reproduce the issue.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.6, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.5.0]
 - deepctr version [e.g. 0.8.6,]

**Additional context**
Add any other context about the problem here.
