### ISSUE TITLE
ValueError: A `Concatenate` layer should be called on a list of at least 2 inputs

### ISSUE THREAD

**Issue by lonngxiang** [shenweichen/DeepCTR#404]
E:\acaconda\envs\tf1\lib\site-packages\deepctr\layers\utils.py in concat_func(inputs, axis, mask)
    185         return inputs[0]
    186     else:
--> 187         return tf.keras.layers.Concatenate(axis=axis)(inputs)
    188 
    189 

E:\acaconda\envs\tf1\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    822           # Build layer if applicable (if the `build` method has been
    823           # overridden).
--> 824           self._maybe_build(inputs)
    825           cast_inputs = self._maybe_cast_inputs(inputs)
    826 

E:\acaconda\envs\tf1\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in _maybe_build(self, inputs)
   2144         # operations.
   2145         with tf_utils.maybe_init_scope(self):
-> 2146           self.build(input_shapes)
   2147       # We must set self.built since user defined build functions are not
   2148       # constrained to set self.built.

E:\acaconda\envs\tf1\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py in wrapper(instance, input_shape)
    304     if input_shape is not None:
    305       input_shape = convert_shapes(input_shape, to_tuples=True)
--> 306     output_shape = fn(instance, input_shape)
    307     # Return shapes from `fn` as TensorShapes.
    308     if output_shape is not None:

E:\acaconda\envs\tf1\lib\site-packages\tensorflow_core\python\keras\layers\merge.py in build(self, input_shape)
    376     # Used purely for shape validation.
    377     if not isinstance(input_shape, list) or len(input_shape) < 2:
--> 378       raise ValueError('A `Concatenate` layer should be called '
    379                        'on a list of at least 2 inputs')
    380     if all(shape is None for shape in input_shape):

ValueError: A `Concatenate` layer should be called on a list of at least 2 inputs

**Comment by zanshuxun** [comment]
Please follow the Bug report template to show your Operating environment and how To Reproduce

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.Better with standalone code to reproduce the issue.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.6, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.5.0]
 - deepctr version [e.g. 0.9.0,]

**Additional context**
Add any other context about the problem here.
