### ISSUE TITLE
DIN构建模型时报错

### ISSUE THREAD

**Issue by Motsen** [shenweichen/DeepCTR#414]
运行din代码，构建模型时报错IndexError: tuple index out of range
[DIN.zip](https://github.com/shenweichen/DeepCTR/files/7211183/DIN.zip)

**Comment by zanshuxun** [comment]
请按照Bug report模板给出更多信息

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.6]
 - torch version [e.g. 1.6.0, 1.7.0]
 - deepctr-torch version [e.g. 0.2.7,]

**Additional context**
Add any other context about the problem here.

**Comment by Motsen** [comment]
Describe the bug(问题描述)
运行din代码，构建模型时报错IndexError: tuple index out of range

To Reproduce(复现步骤)
使用jupyter notebook导入数据并运行代码，在构建din模型时报错IndexError: tuple index out of range

Operating environment(运行环境):

python version 3.9
tensorflow version 2.3.0
deepctr version 0.8.7
