### ISSUE TITLE
Wrong practice when using SequencePoolingLayer in inputs.get_varlen_pooling_list

### ISSUE THREAD

**Issue by ivan-ge677** [shenweichen/DeepCTR#474]
**Describe the bug(问题描述)**
A clear and concise description of what the bug is.Better with standalone code to reproduce the issue.

**To Reproduce(复现步骤)**

**Operating environment(运行环境):**
 - python version [e.g. 3.6, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.5.0]
 - deepctr version [e.g. 0.9.0,]

**Additional context**

**Comment by ivan-ge677** [comment]
row 127 of inputs.get_varlen_pooling_list,vec = SequencePoolingLayer(combiner, supports_masking=True)(seq_input) ,no masking input and supports_masking=True will error
![image](https://user-images.githubusercontent.com/54341458/176115079-7a7dde73-64a0-43d5-a147-283906e4003c.png)

**Comment by zanshuxun** [comment]
please provide more infomation:

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.Better with standalone code to reproduce the issue.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.6, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.5.0]
 - deepctr version [e.g. 0.9.0,]

**Additional context**
Add any other context about the problem here.
