### ISSUE TITLE
Would you please explain VarLenFeat's parameters

### ISSUE THREAD

**Issue by showkeyjar** [shenweichen/DeepCTR#72]
The utils have SingleFeat and VarLenFeat object
but document have not explain the init parameters
just fewer lines in examples.
If I want build a sparse or dense sequence feature, how to set it?

for example:
examples/run_dien.py
behavior_feature_list = ["item", "item_gender"]
"item" and "item_gender" is not like a kind of seq_feature_list

make me confuse.

hope answer

**Comment by shenweichen** [comment]
@showkeyjar  Sorry for the unclear documentation，you can read the doc about `VarlenFeat` in 
https://deepctr-doc.readthedocs.io/en/latest/Examples.html#multi-value-input-movielens

Now, sequence feature only support sparse feature.

For DIN/DIEN the sequence feature config is diffenent from other models that use `VarLenFeat`.
Since DIN/DIEN requires the target vector to match the sequence vector,so features in `feature_dim_dict['sparse']` share embeddings with features in sequence.So we only need to write the name of features in `behavior_feature_list `.
