### ISSUE TITLE
examples/run_dsin.py make me confused

### ISSUE THREAD

**Issue by showkeyjar** [shenweichen/DeepCTR#82]
In example of DSIN, you define a new variable in line 24:
    sess_number = np.array([2, 1, 0])
and add it to the input array:
    x += [sess_number]

but feature_dim_dict did not define this variable's name.

I try to run without it,but get error:
"Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 10 array(s), but instead got the following list of 9 arrays"

why?

what mean of this variable and how to use it?

**Comment by shenweichen** [comment]
`sess_number`is an additional parameter indicating the number of sessions,so it does not need to be included in `feature_dim_dict`

**Comment by showkeyjar** [comment]
so, `sess_number` is the session index? but you just add two sessions:`sess1_item,sess2_item`?

**Comment by showkeyjar** [comment]
I found `sess_number` or `behavior_length` in examples equals `behavior_feature_list` item length which value are not zero. so I guess this parameter looks redundantly. if zero has different meaning.why not use -1 or other interger represent the end of one session?

**Comment by shenweichen** [comment]
@showkeyjar 
hi,I am sorry for didn't reply in time due to recent busy work!
1. `sess_number` is the number of valid sessions of each sample, it is not the session index
2. `sess_number` can be unequal to `behavior_length`,`behavior_length` indicates the max numbers of behavior in each session.
3. `0` is for padding.Because I use `Input()` as placeholder and the `dtype` is not string,so the data in a batch must be equal shape

**Comment by showkeyjar** [comment]
ok,thanks.

**Comment by JWenBin** [comment]
其实还有些细节：
1. sess_number 有可能被理解成这个人总共的sess总数（DSIN定义默认sess_max_count=5），虽然我是理解成当前记录行时间往前的session数，<=5；
2. sess_len_max在定义DSIN的时候有注释到，但却没有实际用到；考虑到example里面定义session物品特征时候maxlen=4，意味着最大值应该是在数据处理开始就限定了序列长度maxlen=4；
